### ISSUE TITLE
To-Do's

### ISSUE THREAD

**Issue by ralfz123** [ralfz123/ring-ring#1]
## Algemeen
- [ ] Parcel (bundler) toepassen (modules index.js)
- [ ] Opschonen importen in index.js en die gebruiken met andere functies in de app

## Data
- [x] Data goed uitzoeken
- [ ] Fetchen async await
- [ ] Load page (onboard page) while receiving data - ease out setTimeOut
- [x] Tooltip: dynamisch data veranderen
- [ ] Reset buttons daadwerkelijk werkend met data
- [ ] Aan de hand van gekozen jaar, map() een array en geef mee aan mapbox en tooltip data

## Introscherm
- [ ] Auto scroll na vid (~7sec)

## Dashboardscherm
- [ ] *transitions/animations toepassen
- [x] [Chart.js](https://www.chartjs.org/) (barchart) toepassen
- [x] [Mapbox](https://www.mapbox.com/) toepassen
- [x] Css GRID toepassen
- [x] legenda passend maken
- [x] Introductie scherm
- [x]   /* -webkit-filter: blur(2px); */ || blurren van background (body) wanneer overlay=true;
- [ ] Iconen in tooltip kleur styling
- [ ] Begin- en eindpunt van routes toevoegen
- [x] resetbutoon padding
- [x] h2 chart padding
- [x] Tooltip misschien weg kunnen klikken?

## Feedbackscherm
- [x] header hetzelfde vormgeven.
- [x] UI styling afronden
- [x] Buttons maken van dropdowns

*= bonus
